services:
  - type: web
    name: omani-therapist-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 60"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: OPENAI_API_KEY
        fromSecret: OPENAI_API_KEY
      - key: GOOGLE_AI_STUDIO_API_KEY
        fromSecret: GOOGLE_AI_STUDIO_API_KEY

  - type: web
    name: omani-therapist-frontend
    env: python
    
    build:
      apt:
        - ffmpeg
        
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run frontend/app.py --server.port $PORT --server.address 0.0.0.0"
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: BACKEND_URL
        fromService:
          type: web
          name: omani-therapist-backend
          property: url